name: Android -PR-Target CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    
permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
   #   - name: checkout
    #    uses: actions/checkout@v4.2.2
     # - name: JDK 17 를 준비한다.
      #  uses: actions/setup-java@v4
       # with:
        #  java-version: '17'
         # distribution: 'temurin'
          #cache: gradle

   #   - name: gradlew 의 root 실행권한을 부여한다.
    #    run: chmod +x gradlew

      #- name: Gradle 을 빌드한다.
      #  run: ./gradlew build --stacktrace

      #- name: 유닛 테스트를 실행한다.
      #  run: ./gradlew test
      - name: Debug Secrets
        env:
          GITHUB_TOKEN: ${{ secrets.IKSEONG_PAT }}
        run: |
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "GITHUB_TOKEN is not set"
          else
            echo "GITHUB_TOKEN is set"
          fi
      - name: rest api 확인
        run: |
          curl -X GET \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/json" \
            https://api.github.com/orgs/OurMenu/repos
      - name: rest api 확인4
        env:
          GITHUB_TOKEN: ${{ secrets.IKSEONG_PAT }}
        run: |
          curl -X GET \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/json" \
            https://api.github.com/orgs/OurMenu/repos
      - name: rest api 확인2
        run: |
          curl -X GET \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/OurMenu/repos
      - name: rest api 확인3
        run: |
          curl -X GET \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/json" \
            https://api.github.com/orgs/OurMenu/repos

      - name: Close Pull Request on Failure
        #if: failure()  # 이전 단계 중 하나라도 실패했을 경우 실행
        env:
          GITHUB_TOKEN: ${{ secrets.IKSEONG_PAT }}
          G_TOKEN: ${{ github.IKSEONG_PAT }}
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
          echo "Actor: ${{ github.actor }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "GIT TOKEN : $GITHUB_TOKEN, G_TOKEN : $G_TOKEN"

          curl -X PATCH \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "User-Agent: OurMenu" \
            -H "Content-Type: application/json" \
            -d '{"state": "close"}' \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}


      - name: Close PR, if build fails # 빌드 실패시 pr 닫기
       # if: ${{ failure() }} # 이전 step이 실패한 경우에만 이 step을 실행시키는 syntax
        uses: actions/github-script@v6
        with: # actions(uses)의 파라미터 역할
          github-token: ${{ github.TOKEN }}
          script: | 
            const pull_number = ${{ github.event.pull_request.number }}
            const updated_title = `[BUILD FAIL] ${{ github.event.pull_request.title }}`
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number,
              body: '빌드에 실패했습니다.',
              event: 'REQUEST_CHANGES'
            })
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number,
              title: updated_title,
              state: 'closed'
            })

      
